[package]
name = "lad_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [lib]
# name = "lad_rs"
# crate-type = ["cdylib"]

[dependencies]
itertools = "0.14.0"
notify-rust = "4.11.7"
polars = "0.52.0"
polars-plan = "0.52.0"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = "1.0.145"

[profile.release]
lto = "fat"
codegen-units = 1
